- name: IaaS Provisioning
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp    
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: 10.0.0.40
      nutanix_username: admin
      nutanix_password: Chicharrones1!
      validate_certs: false
  tasks:
    - name: Include vars file
      include_vars:
        file: vars.yml
    - include_role:
        name: vm