stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "Compiling the code..."
    - mkdir -p /kaniko/.docker
    - |-
       KANIKOPROXYBUILDARGS=""
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo "${LOCAL_CA}" >> /kaniko/ssl/certs/additional-ca-cert-bundle.crt
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/dockerfile"
      "${KANIKOPROXYBUILDARGS}"
      --destination "${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
    - echo "Compile complete."
